# Config dosyası
webhookUrl: "WEBHOOK_URL_HERE"
mysql:
  host: "localhost"
  port: 3306
  database: "yourdatabase"
  username: "username"
  password: "password"
worlds:
  - world
  - world_nether
  - world_the_end
blockMessages:
  SPAWNER:
    message: "**SPAWNER KIRILDI!** \nOyuncu: {player}, \nKoordinatlar: X: {x}, Y: {y}, Z: {z}"
    color: 7185242 #colors for https://www.mathsisfun.com/hexadecimal-decimal-colors.html
  ANCIENT_DEBRIS:
    message: "**ANTİK KALINTI KIRILDI!** \nOyuncu: {player}, \nKoordinatlar: X: {x}, Y: {y}, Z: {z}"
    color: 7185242 #colors for https://www.mathsisfun.com/hexadecimal-decimal-colors.html
  DIAMOND_ORE:
    message: "**BREAK DIAMOND ORE!** \nPLAYER NAME: {player}, \nCORDI: X: {x}, Y: {y}, Z: {z}"
    color: 7185242
# add new block
